# Generated by Django 4.1.7 on 2023-03-20 13:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
