# Generated by Django 4.1.7 on 2023-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landsize_sqm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
